### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by lspxsy** [vue-icons-plus/vue-icons-plus#2]
* vue-icons-plus/ai in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!

![1724395210932](https://github.com/user-attachments/assets/e05901b8-11e3-46eb-a91a-885690b47847)
![image](https://github.com/user-attachments/assets/f6bda38b-30d7-4108-91e1-40eb6cc6cfec)

**Comment by dwanl** [comment]
Okay, thank you. This issue may occur with lower version build tools. I will fix it

**Comment by dwanl** [comment]
Can you please check the version of webpack?

**Comment by lspxsy** [comment]
vue-cli version
![image](https://github.com/user-attachments/assets/02503263-8da5-4976-863f-2b3bb83e818a)

webpack version
![image](https://github.com/user-attachments/assets/6b4172be-f8f3-4f04-8a5c-3f73b88beb16)
