### ISSUE TITLE
嵌套在el-dropdown里面为什么会这样，有个边框

### ISSUE THREAD

**Issue by iCloudys** [vue-icons-plus/vue-icons-plus#5]
![图片](https://github.com/user-attachments/assets/ac55a93e-a3e7-4590-96ca-08836570d8cf)

**Comment by iCloudys** [comment]
![图片](https://github.com/user-attachments/assets/01d7e244-fa2d-4734-ae5a-17db3e6f2a0d)

**Comment by dwanl** [comment]
`user agent stylesheet` 是浏览器默认样式，跟 el 框架没关系，可以通过 `outline: none;` 覆盖掉

**Comment by dwanl** [comment]
> ![图片](https://private-user-images.githubusercontent.com/13017318/360932381-01d7e244-fa2d-4734-ae5a-17db3e6f2a0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MzQ1ODksIm5iZiI6MTcyNDYzNDI4OSwicGF0aCI6Ii8xMzAxNzMxOC8zNjA5MzIzODEtMDFkN2UyNDQtZmEyZC00NzM0LWFlNWEtMTdkYjNlNmYyYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAxMDQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwODdlNmNkNDYyYjdjMTU5NTlmNzg0ODFjZWQ3ZDRlZDNmNGE2NTEyOGQ3MjVjOTNiNDI4YjliMmQxZWZlODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A5Engvq2njDTLLxMTaJkvplQUU03cd64fvoaXS8QIzg)

`user agent stylesheet` 是浏览器默认样式，跟 el 框架没关系，可以通过 `outline: none;` 覆盖掉
