### ISSUE TITLE
Can't install in project with Vue 3.5.11

### ISSUE THREAD

**Issue by DanielHudson** [vue-icons-plus/vue-icons-plus#9]
`npm install vue-icons-plus --save-dev`

I can't install vue-icons-plus in a project with Vue 3.5.11, as it results in the following.

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: undefined@undefined
npm error Found: vue@3.5.12
npm error node_modules/vue
npm error   dev vue@"^3.5.11" from the root project
npm error
npm error Could not resolve dependency:
npm error peer vue@"^2.7.0" from vue-icons-plus@0.1.6
npm error node_modules/vue-icons-plus
npm error   dev vue-icons-plus@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/user/.npm/_logs/2024-10-26T14_49_32_513Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/user/.npm/_logs/2024-10-26T14_49_32_513Z-debug-0.log
```

I can get around this for now by using `npm install vue-icons-plus --save-dev --legacy-peer-deps`

**Comment by dwanl** [comment]
> `npm install vue-icons-plus --save-dev`
> 
> I can't install vue-icons-plus in a project with Vue 3.5.11, as it results in the following.
> 
> ```
> npm error code ERESOLVE
> npm error ERESOLVE unable to resolve dependency tree
> npm error
> npm error While resolving: undefined@undefined
> npm error Found: vue@3.5.12
> npm error node_modules/vue
> npm error   dev vue@"^3.5.11" from the root project
> npm error
> npm error Could not resolve dependency:
> npm error peer vue@"^2.7.0" from vue-icons-plus@0.1.6
> npm error node_modules/vue-icons-plus
> npm error   dev vue-icons-plus@"*" from the root project
> npm error
> npm error Fix the upstream dependency conflict, or retry
> npm error this command with --force or --legacy-peer-deps
> npm error to accept an incorrect (and potentially broken) dependency resolution.
> npm error
> npm error
> npm error For a full report see:
> npm error /Users/user/.npm/_logs/2024-10-26T14_49_32_513Z-eresolve-report.txt
> npm error A complete log of this run can be found in: /Users/user/.npm/_logs/2024-10-26T14_49_32_513Z-debug-0.log
> ```
> 
> I can get around this for now by using `npm install vue-icons-plus --save-dev --legacy-peer-deps`

Oh, I understand, the reason is caused by the setting of `peerDependencies: "^ 2.7.0"`. Changing it to `"peerDependencies: ">=2.7.0 "`  should solve it. I will fix it

**Comment by DanielHudson** [comment]
Thank you!
